# 启动命令行参数占位符的默认值
cmd:
  server: "127.0.0.1"
  mysql:
    ip: "localhost"

swagger:
  contact:
    name: "Gateway Coder"
    url: "http://github.com"
    email: "123@126.com"

server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: sparrow-zuul-gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    host: "localhost"
  ##    url: "192.168.3.17"
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://${cmd.mysql.ip}:3306/sparrow?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: org.ly817.sparrow.api.pojo
  configuration:
    map-underscore-to-camel-case: true
debug: true
#  profiles:
#    active: dev # 会被spring.cloud.config.profile指定的远程配置文件替代
