# 启动命令行参数占位符的默认值
cmd:
  server: "127.0.0.1"

server:
  port: 8080
  
spring:
  application:
    name: sparrow-gateway
  main:
      allow-bean-definition-overriding: true
debug: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver