# 启动命令行参数占位符的默认值
cmd:
  server: "127.0.0.1"

server:
  port: 10000
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: sparrow-ms-admin

  redis:
    host: "localhost"
##    url: "192.168.3.17"
debug: false
#  profiles:
#    active: dev # 会被spring.cloud.config.profile指定的远程配置文件替代
