# 启动命令行参数占位符的默认值
cmd:
  server: "127.0.0.1"
  push:
    port: 8000

# 微服务负责人联系方式
swagger:
  contact:
    name: "User Coder"
    url: "http://github.com"
    email: "123@126.com"

server:
  port: 18000
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: sparrow-ws-push
  redis:
    host: "192.168.56.101"
##    url: "192.168.3.17"


#debug: true
rocketmq:
  name-server: localhost:9876

#  profiles:
#    active: dev # 会被spring.cloud.socketio.profile指定的远程配置文件替代
