# 启动命令行参数占位符的默认值
cmd:
  server: "127.0.0.1"
  push:
    port: 8000

server:
  port: 18000
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: sparrow-ws-push
  redis:
    host: "192.168.56.101"
##    url: "192.168.3.17"


debug: true
rocketmq:
  name-server: 192.168.56.101:9876

#  profiles:
#    active: dev # 会被spring.cloud.socketio.profile指定的远程配置文件替代
