# 启动命令行参数占位符的默认值
cmd:
  server: "127.0.0.1"
  mysql:
    ip: "localhost"

#server:
#  port: 10009
management:
  endpoints:
    web:
      base-path: /
spring:
  application:
    name: sparrow-ws-push
  redis:
    host: "localhost"
##    url: "192.168.3.17"

debug: true

#  profiles:
#    active: dev # 会被spring.cloud.socketio.profile指定的远程配置文件替代
