FROM mysql:5.6

LABEL author="luoyu817"
LABEL email="luoyu817@126.com"


# 声明工作目录
ENV WORK_PATH /usr/local/work
#声明会被容器自动执行的目录环境变量 由mysql官方镜像提供
ENV AUTO_RUN_DIR /docker-entrypoint-initdb.d
ENV FILE_0 sparrow.sql
ENV FILE_1 sparrow-20191027.sql
ENV FILE_2 sparrow-20191119-plugin.sql
ENV FILE_3 sparrow-20191222-gateway_api_route.sql
#声明shell文件名
ENV INSTALL_DATA_SHELL sparrow-sql-bootstrap.sh


# 待执行sql脚本
COPY ./$FILE_0 $WORK_PATH/
COPY ./$FILE_1 $WORK_PATH/
COPY ./$FILE_2 $WORK_PATH/
COPY ./$FILE_3 $WORK_PATH/

# 带执行sh脚本
COPY ./$INSTALL_DATA_SHELL $AUTO_RUN_DIR/

#给执行文件增加可执行权限
RUN chmod a+x $AUTO_RUN_DIR/$INSTALL_DATA_SHELL
