FROM java:openjdk-8-jre
LABEL author="luoyu817"
LABEL email="luoyu817@126.com"

ADD ./target/sparrow-eureka-server-0.0.1-SNAPSHOT.jar /usr/local/app.jar
ADD ./docker-bootstrap.sh /usr/local/docker-bootstrap.sh 

EXPOSE 8761

ENTRYPOINT [ "sh","/usr/local/docker-bootstrap.sh" ]